FROM nginx:stable

RUN apt-get update && apt-get install -y gettext-base

COPY nginx.conf.template /etc/nginx/templates/nginx.conf.template

CMD ["/bin/sh", "-c", "envsubst '$APP_PORT' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
