server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # --- ВКЛЮЧЕНИЕ СЖАТИЯ (GZIP) ---
    gzip on;
    gzip_disable "msie6";

    # Уровень сжатия (1-9). 5 или 6 — золотая середина между CPU и размером.
    gzip_comp_level 6;

    # Минимальный размер файла для сжатия (в байтах).
    gzip_min_length 256;

    # Сжимаем проксированные запросы тоже
    gzip_proxied any;

    # Типы файлов, которые нужно сжимать (HTML сжимается по умолчанию)
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        image/svg+xml; # Важно! Сжимаем SVG логотипы

    # Добавляем заголовок Vary, чтобы кэши учитывали сжатие
    gzip_vary on;
    # --------------------------------

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }

    # Кэширование статики
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|webp|woff|woff2|ttf|eot)$ {
    expires 0; # Отключаем кэш или ставим маленькое значение
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
